package org.mz.killrs.shared.component

data class StateOfUs(
    val name: String,
    val abbreviation: String
)

val statesOfUs = listOf(
    StateOfUs("Alabama", "AL"),
    StateOfUs("Alaska", "AK"),
    StateOfUs("Arizona", "AZ"),
    StateOfUs("Arkansas", "AR"),
    StateOfUs("California", "CA"),
    StateOfUs("Colorado", "CO"),
    StateOfUs("Connecticut", "CT"),
    StateOfUs("Delaware", "DE"),
    StateOfUs("Florida", "FL"),
    StateOfUs("Georgia", "GA"),
    StateOfUs("Hawaii", "HI"),
    StateOfUs("Idaho", "ID"),
    StateOfUs("Illinois", "IL"),
    StateOfUs("Indiana", "IN"),
    StateOfUs("Iowa", "IA"),
    StateOfUs("Kansas", "KS"),
    StateOfUs("Kentucky", "KY"),
    StateOfUs("Louisiana", "LA"),
    StateOfUs("Maine", "ME"),
    StateOfUs("Maryland", "MD"),
    StateOfUs("Massachusetts", "MA"),
    StateOfUs("Michigan", "MI"),
    StateOfUs("Minnesota", "MN"),
    StateOfUs("Mississippi", "MS"),
    StateOfUs("Missouri", "MO"),
    StateOfUs("Montana", "MT"),
    StateOfUs("Nebraska", "NE"),
    StateOfUs("Nevada", "NV"),
    StateOfUs("New Hampshire", "NH"),
    StateOfUs("New Jersey", "NJ"),
    StateOfUs("New Mexico", "NM"),
    StateOfUs("New York", "NY"),
    StateOfUs("North Carolina", "NC"),
    StateOfUs("North Dakota", "ND"),
    StateOfUs("Ohio", "OH"),
    StateOfUs("Oklahoma", "OK"),
    StateOfUs("Oregon", "OR"),
    StateOfUs("Pennsylvania", "PA"),
    StateOfUs("Rhode Island", "RI"),
    StateOfUs("South Carolina", "SC"),
    StateOfUs("South Dakota", "SD"),
    StateOfUs("Tennessee", "TN"),
    StateOfUs("Texas", "TX"),
    StateOfUs("Utah", "UT"),
    StateOfUs("Vermont", "VT"),
    StateOfUs("Virginia", "VA"),
    StateOfUs("Washington", "WA"),
    StateOfUs("West Virginia", "WV"),
    StateOfUs("Wisconsin", "WI"),
    StateOfUs("Wyoming", "WY")
)